### ISSUE TITLE
ng2-admin ng2websocket 报错

### ISSUE THREAD

**Issue by yinsua** [vanishs/ng2websocket#1]
你好，我在ng2-admin （[链接](https://akveo.github.io/ng2-admin/)） 项目中添加了ng2websocket，但是报错了：
`[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\angular2\typings\browser.d.ts:6:14 
    Duplicate identifier 'PromiseConstructor'.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\angular2\typings\es6-collections\es6-collections.d.ts:23:5 
    All declarations of 'value' must have identical modifiers.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\angular2\typings\es6-collections\es6-collections.d.ts:46:5 
    All declarations of 'size' must have identical modifiers.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\angular2\typings\es6-collections\es6-collections.d.ts:52:5 
    All declarations of 'prototype' must have identical modifiers.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\angular2\typings\es6-collections\es6-collections.d.ts:66:5 
    All declarations of 'size' must have identical modifiers.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\angular2\typings\es6-collections\es6-collections.d.ts:72:5 
    All declarations of 'prototype' must have identical modifiers.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\angular2\typings\es6-collections\es6-collections.d.ts:88:5 
    All declarations of 'prototype' must have identical modifiers.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\angular2\typings\es6-collections\es6-collections.d.ts:103:5 
    All declarations of 'prototype' must have identical modifiers.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\angular2\typings\es6-promise\es6-promise.d.ts:11:15 
    Duplicate identifier 'Promise'.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\angular2\typings\es6-promise\es6-promise.d.ts:42:16 
    Duplicate identifier 'Promise'.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\typescript\lib\lib.es2015.iterable.d.ts:121:11 
    Duplicate identifier 'Promise'.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\typescript\lib\lib.es2015.iterable.d.ts:123:11 
    Duplicate identifier 'PromiseConstructor'.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\typescript\lib\lib.es2015.promise.d.ts:20:11 
    Duplicate identifier 'Promise'.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\typescript\lib\lib.es2015.promise.d.ts:65:11 
    Duplicate identifier 'PromiseConstructor'.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\typescript\lib\lib.es2015.promise.d.ts:187:13 
    Duplicate identifier 'Promise'.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\typescript\lib\lib.es2015.symbol.wellknown.d.ts:164:11 
    Duplicate identifier 'Promise'.
[default] C:\Users\Administrator\WebstormProjects\ng2-admin\node_modules\typescript\lib\lib.es2015.symbol.wellknown.d.ts:168:11 
    Duplicate identifier 'PromiseConstructor'.
[default] Checking finished with 17 errors`

我把ng2websocket移除就好了，请问是什么问题？谢谢

**Comment by yinsua** [comment]
已解决
注释掉ng2websocket模块的ng2websocket.ts中
`/// <reference path="../../node_modules/angular2/core.d.ts" />
///<reference path="../../node_modules/angular2/typings/browser.d.ts"/>`
即可

**Comment by vanishs** [comment]
@yinsua 非常抱歉！这个模块是在学习ng2阶段非常不严谨的试验品，里面有对ng2非常糟糕的理解和设计。可以这么说，这是一个非常错误的设计方向，所以我将会删除掉该项目。对此先向大家道歉，请有需要的人找到更加合适的库 或者移步至 [https://github.com/vanishs/umdwebsocket](url)
